# Generated by Django 4.0.1 on 2022-01-14 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('group', models.CharField(choices=[('total anarchy', 'TOTAL ANARCHY'), ('empathatic anarchy', 'EMPATHATIC ANARCHY'), ('constrained anarchy', 'CONSTRAINED ANARCHY'), ('nihilist anarchy', 'NIHILIST ANARCHY')], default='total anarchy', max_length=25)),
                ('message', models.TextField(default='', max_length=512)),
                ('statanic_god_supporter', models.CharField(choices=[('christian theological god', 'CHRISTIAN THEOLOGICAL GOD'), ('christian theological devil', 'CHRISTIAN THEOLOGICAL DEVIL'), ('satan', 'SATAN'), ('tiamat', 'TIAMAT'), ('cronus', 'CRONUS')], default='satan', max_length=64)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
